language: ruby
rvm:
  - 1.9.2
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

# .travis.yml
before_script:
  - "mysql -e 'create database testman_test; grant all on testman_test.* to 'testman'@'localhost' identified by 'testman''"