# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: testman_development
  pool: 5
  username: testman
  password: testman
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: testman_test
  pool: 5
  username: testman
  password: testman
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: testman_production
  pool: 5
  username: testman
  password: testman
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *test